### PR TITLE
Added paragraph and header fields also with className parameter

### PR DESCRIPTION
**Pull request by Mte90**
With a new custom field/widget for pure HTML output using the FormBuilerUI data structure

### CODE REVIEW

**Review by askvortsov1 — APPROVED** [review]
Thank you very much!

**Comment by Mte90** [comment]
Can you plan to do a new release with this change? so I can use the latest package version :-)

**Comment by askvortsov1** [comment]
> Can you plan to do a new release with this change? so I can use the latest package version :-)

I'm pretty sure I released v0.1.7 with these changes, are they not working there?

**Comment by Mte90** [comment]
I see that on github the latest release is 0.1.2 https://github.com/askvortsov1/dynamic-django-forms/releases

**Comment by askvortsov1** [comment]
> I see that on github the latest release is 0.1.2 https://github.com/askvortsov1/dynamic-django-forms/releases

Right, I released directly to pypi, and only tagged on GitHub.

https://pypi.org/project/dynamic-django-forms/#history

**Comment by Mte90** [comment]
Ok perfect as from GitHub not was clear the status for the releases :-)

**Pull request merged**
